service: nasa-search
provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors:
            origin: "*"
            headers:
            - "Content-Type"
            - "Cache-Control"
            - "Expires"
            - "Pragma"
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            headers:
            - "Content-Type"
            - "Cache-Control"
            - "Expires"
            - "Pragma"