service: nasa-search

package:
  individually: true
  patterns:
    - "!./**"
    - ./dist/**
    - ./package.json

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  memorySize: 128
  environment:
    API_URL: ${myAwsAccount:ssm:/nasa-search/api-url}
    NODE_ENV: production

stages:
  default:
    resolvers:
      myAwsAccount:
        type: aws

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: "*"
            headers:
            - "Content-Type"
            - "Cache-Control"
            - "Expires"
            - "Pragma"
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            headers:
            - "Content-Type"
            - "Cache-Control"
            - "Expires"
            - "Pragma"
